<a href="https://colab.research.google.com/github/marcewp15/Proyecto-Final-Data-Xperience/blob/main/Proyecto_Final_DataX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Internet_Fijo_Accesos.csv") #lee el archivo csv

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614227 entries, 0 to 614226
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   AÑO               614227 non-null  int64
 1   TRIMESTRE         614227 non-null  int64
 2   PROVEEDOR         614227 non-null  object
 3   COD_DEPARTAMENTO  614227 non-null  int64
 4   DEPARTAMENTO      614227 non-null  object
 5   COD_MUNICIPIO     614227 non-null  int64
 6   MUNICIPIO         614227 non-null  object
 7   SEGMENTO          614227 non-null  object
 8   TECNOLOGIA        614227 non-null  object
 9   VELOCIDAD_BAJADA  614227 non-null  object
 10  VELOCIDAD_SUBIDA  614227 non-null  object
 11  No DE ACCESOS     614227 non-null  int64
dtypes: int64(5), object(7)
memory usage: 56.2+ MB

In [ ]:
df.head()

,AÑO,TRIMESTRE,PROVEEDOR,COD_DEPARTAMENTO,DEPARTAMENTO,COD_MUNICIPIO,MUNICIPIO,SEGMENTO,TECNOLOGIA,VELOCIDAD_BAJADA,VELOCIDAD_SUBIDA,No DE ACCESOS
0,2023,2,DIRECTV COLOMBIA LTDA,8,ATLÁNTICO,8520,PALMAR DE VARELA,RESIDENCIAL - ESTRATO 1,OTRAS TECNOLOGÍAS INALÁMBRICAS,"6,00","1,00",3
1,2023,3,DIFUDATOS S A S,25,CUNDINAMARCA,25224,CUCUNUBÁ,CORPORATIVO,OTRAS TECNOLOGÍAS INALÁMBRICAS,"30,00","24,00",1
2,2023,3,COMUNICACION CELULAR S A COMCEL S A,5,ANTIOQUIA,5079,BARBOSA,RESIDENCIAL - ESTRATO 2,CABLE,"30,00","5,00",102
3,2023,2,ACHITEL SAS,13,BOLÍVAR,13006,ACHÍ,RESIDENCIAL - ESTRATO 1,FIBER TO THE HOME (FTTH),"12,00","12,00",3
4,2023,3,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,76,VALLE DEL CAUCA,76001,CALI,RESIDENCIAL - ESTRATO 6,FIBER TO THE HOME (FTTH),"600,00","256,00",12

In [ ]:
df.columns

Index(['AÑO', 'TRIMESTRE', 'PROVEEDOR', 'COD_DEPARTAMENTO', 'DEPARTAMENTO',
       'COD_MUNICIPIO', 'MUNICIPIO', 'SEGMENTO', 'TECNOLOGIA',
       'VELOCIDAD_BAJADA', 'VELOCIDAD_SUBIDA', 'No DE ACCESOS'],
      dtype='object')

In [ ]:
df = df.drop(columns=["COD_DEPARTAMENTO", "COD_MUNICIPIO"])

In [ ]:
df

,AÑO,TRIMESTRE,PROVEEDOR,DEPARTAMENTO,MUNICIPIO,SEGMENTO,TECNOLOGIA,VELOCIDAD_BAJADA,VELOCIDAD_SUBIDA,No DE ACCESOS
0,2023,2,DIRECTV COLOMBIA LTDA,ATLÁNTICO,PALMAR DE VARELA,RESIDENCIAL - ESTRATO 1,OTRAS TECNOLOGÍAS INALÁMBRICAS,"6,00","1,00",3
1,2023,3,DIFUDATOS S A S,CUNDINAMARCA,CUCUNUBÁ,CORPORATIVO,OTRAS TECNOLOGÍAS INALÁMBRICAS,"30,00","24,00",1
2,2023,3,COMUNICACION CELULAR S A COMCEL S A,ANTIOQUIA,BARBOSA,RESIDENCIAL - ESTRATO 2,CABLE,"30,00","5,00",102
3,2023,2,ACHITEL SAS,BOLÍVAR,ACHÍ,RESIDENCIAL - ESTRATO 1,FIBER TO THE HOME (FTTH),"12,00","12,00",3
4,2023,3,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,VALLE DEL CAUCA,CALI,RESIDENCIAL - ESTRATO 6,FIBER TO THE HOME (FTTH),"600,00","256,00",12
...,...,...,...,...,...,...,...,...,...,...
614222,2023,1,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,TOLIMA,IBAGUÉ,RESIDENCIAL - ESTRATO 4,FIBER TO THE HOME (FTTH),"400,00","409,00",5
614223,2023,1,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,SANTANDER,BUCARAMANGA,RESIDENCIAL - ESTRATO 4,XDSL,"4,00","4,00",6
614224,2023,3,COMUNICACION CELULAR S A COMCEL S A,CUNDINAMARCA,CHÍA,RESIDENCIAL - ESTRATO 2,CABLE,"200,00","30,00",3
614225,2023,3,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,SANTANDER,PIEDECUESTA,RESIDENCIAL - ESTRATO 6,FIBER TO THE HOME (FTTH),"700,00","409,00",1
614226,2023,3,COLOMBIA TELECOMUNICACIONES S.A. E.S.P.,ANTIOQUIA,SABANETA,RESIDENCIAL - ESTRATO 3,FIBER TO THE HOME (FTTH),"500,00","358,00",6